/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Media = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ObjectMedia = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ItemsObjectMedia = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "items.object.media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  overlay?: boolean;
  whiteTexts?: boolean;
  _type: "image";
};

export type ItemsObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ContentSelectRevealMediaItemsObjectMedia = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "contentSelectRevealMedia.items.object.media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ContentTabsMediaItemsObjectMedia = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "contentTabsMedia.items.object.media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ShowcaseGridImageCardsItemsObjectMedia = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "showcaseGridImageCards.items.object.media.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type ShowcaseGridImageCards = {
  _type: "showcaseGridImageCards";
  title?: string;
  items?: Array<{
    title?: string;
    description?: string;
    media?: ShowcaseGridImageCardsItemsObjectMedia;
    _key: string;
  }>;
  cta?: Cta;
};

export type HeroContentMedia = {
  _type: "heroContentMedia";
  title?: string;
  description?: string;
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryCTA?: Cta;
  secondaryCTA?: Cta;
};

export type HeroTextBadges = {
  _type: "heroTextBadges";
  title?: string;
  primaryCTA?: Cta;
  secondaryCTA?: Cta;
  features?: Array<{
    title?: string;
    _key: string;
  }>;
};

export type HeroBackgroundMedia = {
  _type: "heroBackgroundMedia";
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  cta?: Cta;
  whiteTexts?: boolean;
};

export type ContentTitleWithMedia = {
  _type: "contentTitleWithMedia";
  title?: string;
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ContentIconList = {
  _type: "contentIconList";
  title?: string;
  items?: Array<{
    title?: string;
    icon?: string;
    _key: string;
  }>;
};

export type ContentGridWithMediaTop = {
  _type: "contentGridWithMediaTop";
  title?: string;
  description?: string;
  cta?: Cta;
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  items?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type ContentTabsMedia = {
  _type: "contentTabsMedia";
  title?: string;
  description?: string;
  items?: Array<{
    label?: string;
    media?: ContentTabsMediaItemsObjectMedia;
    _key: string;
  }>;
};

export type ContentSelectRevealMedia = {
  _type: "contentSelectRevealMedia";
  items?: Array<{
    title?: string;
    description?: string;
    media?: ContentSelectRevealMediaItemsObjectMedia;
    imageAlt?: string;
    _key: string;
  }>;
};

export type ContentGridTwoColumns = {
  _type: "contentGridTwoColumns";
  title?: string;
  content?: string;
  media?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ContentFocusGrid = {
  _type: "contentFocusGrid";
  title?: string;
  description?: string;
  items?: Array<{
    title?: string;
    description?: string;
    image?: ItemsObjectImage;
    defaultFocus?: boolean;
    _key: string;
  }>;
  dimUnfocused?: boolean;
  descriptionOnFocus?: boolean;
};

export type ContentGridMediaCards = {
  _type: "contentGridMediaCards";
  title?: string;
  items?: Array<{
    title?: string;
    description?: string;
    image?: ObjectImage;
    icon?: string;
    _key: string;
  }>;
};

export type ContentGridContentColumns = {
  _type: "contentGridContentColumns";
  items?: Array<{
    media?: ItemsObjectMedia;
    title?: string;
    content?: string;
    cta?: Cta;
    _key: string;
  }>;
};

export type ContentGridCards = {
  _type: "contentGridCards";
  title?: string;
  items?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type ContentCenteredText = {
  _type: "contentCenteredText";
  title?: string;
  description?: string;
  cta?: Cta;
};

export type ContentBadgeList = {
  _type: "contentBadgeList";
  title?: string;
  description?: string;
  items?: Array<{
    title?: string;
    _key: string;
  }>;
};

export type CarouselMedia = {
  _type: "carouselMedia";
  title?: string;
  description?: string;
  items?: Array<{
    media?: ObjectMedia;
    title?: string;
    description?: string;
    whiteTexts?: boolean;
    _key: string;
  }>;
  showNavigation?: boolean;
};

export type CarouselFocus = {
  _type: "carouselFocus";
  titlePlacement?: "inside" | "outside";
  items?: Array<{
    title?: string;
    media?: Media;
    aspect?: "landscape" | "portrait" | "wide";
    _key: string;
  }>;
};

export type Cta = {
  _type: "cta";
  ctaEnabled?: boolean;
  text?: string;
  link?: string;
  variant?: "default" | "secondary" | "outline" | "ghost" | "link";
};

export type Blocks = Array<
  | ({
      _key: string;
    } & ContentBadgeList)
  | ({
      _key: string;
    } & CarouselFocus)
  | ({
      _key: string;
    } & CarouselMedia)
  | ({
      _key: string;
    } & ContentCenteredText)
  | ({
      _key: string;
    } & ContentGridCards)
  | ({
      _key: string;
    } & ContentGridContentColumns)
  | ({
      _key: string;
    } & ContentGridMediaCards)
  | ({
      _key: string;
    } & ContentFocusGrid)
  | ({
      _key: string;
    } & ContentGridTwoColumns)
  | ({
      _key: string;
    } & ContentSelectRevealMedia)
  | ({
      _key: string;
    } & ContentTabsMedia)
  | ({
      _key: string;
    } & ContentGridWithMediaTop)
  | ({
      _key: string;
    } & ContentIconList)
  | ({
      _key: string;
    } & ContentTitleWithMedia)
  | ({
      _key: string;
    } & HeroBackgroundMedia)
  | ({
      _key: string;
    } & HeroTextBadges)
  | ({
      _key: string;
    } & HeroContentMedia)
  | ({
      _key: string;
    } & ShowcaseGridImageCards)
>;

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  blocks?: Blocks;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Media
  | ObjectMedia
  | ItemsObjectMedia
  | ObjectImage
  | ItemsObjectImage
  | ContentSelectRevealMediaItemsObjectMedia
  | ContentTabsMediaItemsObjectMedia
  | ShowcaseGridImageCardsItemsObjectMedia
  | ShowcaseGridImageCards
  | HeroContentMedia
  | HeroTextBadges
  | HeroBackgroundMedia
  | ContentTitleWithMedia
  | ContentIconList
  | ContentGridWithMediaTop
  | ContentTabsMedia
  | ContentSelectRevealMedia
  | ContentGridTwoColumns
  | ContentFocusGrid
  | ContentGridMediaCards
  | ContentGridContentColumns
  | ContentGridCards
  | ContentCenteredText
  | ContentBadgeList
  | CarouselMedia
  | CarouselFocus
  | Cta
  | Blocks
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;
